'use strict';const $=id=>document.getElementById(id);let state={traitements:[],agents:[],config:{}},selectedIds=new Set();
const date=v=>v?new Date(v).toLocaleString('fr-FR'):'—';const duration=s=>s==null?'—':[Math.floor(s/3600),Math.floor(s%3600/60),Math.floor(s%60)].map(v=>String(v).padStart(2,'0')).join(':');
async function api(path,body){const payload=body?JSON.stringify(body).replace(/[\u007f-\uffff]/g,c=>'\\u'+c.charCodeAt(0).toString(16).padStart(4,'0')):null;const r=await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:payload}:{});const x=await r.json();if(!r.ok)throw Error(x.erreur||'Erreur');return x}function msg(t,e=false){$('message').hidden=false;$('message').textContent=t;$('message').className=e?'error':''}
function td(v){const x=document.createElement('td');x.textContent=v??'—';return x}function status(v){const x=document.createElement('span');x.className='status';x.textContent=v;return x}
function render(){const rows=state.traitements||[],queue=rows.filter(r=>!r.agent&&!r.dateFin),active=rows.filter(r=>r.agent&&!r.dateFin),done=rows.filter(r=>!!r.dateFin||r.statut==='Terminé');$('kTotal').textContent=rows.length;$('kQueue').textContent=queue.length;$('navQueue').textContent=queue.length;$('kActive').textContent=active.length;$('kDone').textContent=done.length;$('kDmt').textContent=duration(done.length?done.reduce((s,r)=>s+(Number(r.dmtSecondes)||0),0)/done.length:null);$('sourceDirectory').value=state.config?.sourceDirectory||'';
 {const current=$('agentName').value;$('agentName').replaceChildren(new Option('Choisir un agent',''),...(state.agents||[]).map(a=>new Option(a,a)));if((state.agents||[]).includes(current))$('agentName').value=current}const queueIds=new Set(queue.map(r=>r.id));selectedIds=new Set([...selectedIds].filter(id=>queueIds.has(id)));$('queueRows').replaceChildren();for(const r of queue){const tr=document.createElement('tr'),check=document.createElement('input');check.type='checkbox';check.value=r.id;check.className='pick';check.checked=selectedIds.has(r.id);check.onchange=()=>{if(check.checked)selectedIds.add(r.id);else selectedIds.delete(r.id);$('selectAll').checked=queue.length>0&&selectedIds.size===queue.length};const c=td('');c.append(check);tr.append(c,td(r.sourceFile),td(r.raisonSociale),td(r.siret),td(r.typeFacture||'—'),td(r.dateLimite||'—'));$('queueRows').append(tr)}$('selectAll').checked=queue.length>0&&selectedIds.size===queue.length;$('queueEmpty').hidden=queue.length>0;
 $('assignedRows').replaceChildren();for(const r of active){const tr=document.createElement('tr');tr.append(td(r.agent),td(r.raisonSociale),td(r.siret),td(r.sourceFile));const s=td('');s.append(status(r.statut));tr.append(s,td(date(r.dateAffectation)));$('assignedRows').append(tr)}renderDone();renderCharts(rows)}
function renderDone(){const q=$('search').value.toLowerCase(),done=state.traitements.filter(r=>r.dateFin&&[r.agent,r.raisonSociale,r.siret,r.sourceFile,r.typeFacture,r.numeroAbonne].join(' ').toLowerCase().includes(q));$('doneRows').replaceChildren();for(const r of done){const tr=document.createElement('tr');tr.append(td(r.agent),td(r.raisonSociale),td(r.siret),td(r.numeroAbonne),td(r.idt),td(r.contratBad),td(r.csp),td(duration(r.dmtSecondes)),td(date(r.dateFin)));$('doneRows').append(tr)}}
function donut(chartId,legendId,groups,total){let p=0;const base=Math.max(1,total);const slices=groups.map(g=>{const a=p;p+=g[1]/base*100;return`${g[2]} ${a}% ${p}%`});$(chartId).style.background=groups.some(g=>g[1])?`conic-gradient(${slices.join(',')})`:'#e7edf2';$(legendId).replaceChildren(...groups.map(g=>{const x=document.createElement('div');x.className='legend';x.innerHTML=`<span><i style="background:${g[2]}"></i>${g[0]}</span><b>${g[1]}</b>`;return x}))}
function renderCharts(rows){const done=rows.filter(r=>!!r.dateFin),map=new Map;for(const r of done){const name=r.agent||'Non renseigné';map.set(name,(map.get(name)||0)+1)}const max=Math.max(1,...map.values());$('agentChart').replaceChildren();for(const [name,count]of[...map].sort((a,b)=>b[1]-a[1])){const row=document.createElement('div');row.className='bar';row.innerHTML=`<span>${name}</span><div class="track"><div class="fill" style="width:${count/max*100}%"></div></div><b>${count}</b>`;$('agentChart').append(row)}if(!map.size)$('agentChart').textContent='Aucun traitement terminé.';const palette=['#e7652b','#58a735','#174d75','#92bf2d','#9b6bc8','#e0a42b','#5b9bd5'],types=new Map;for(const r of rows){const name=String(r.typeFacture||'Non renseigné').trim()||'Non renseigné';types.set(name,(types.get(name)||0)+1)}const typeGroups=[...types].sort((a,b)=>b[1]-a[1]).map((g,i)=>[g[0],g[1],palette[i%palette.length]]);donut('typeChart','typeLegend',typeGroups,rows.length);const groups=[['Terminées',done.length,'#58a735'],['En cours',rows.filter(r=>r.agent&&!r.dateFin).length,'#e7652b'],['À affecter',rows.filter(r=>!r.agent&&!r.dateFin).length,'#9ab0c4']];donut('statusChart','statusLegend',groups,rows.length)}
async function refresh(){try{state=await api('state');state.traitements=(Array.isArray(state.traitements)?state.traitements:[state.traitements]).flat(Infinity).filter(x=>x&&typeof x==='object');state.agents=(Array.isArray(state.agents)?state.agents:[state.agents]).flat(Infinity).filter(Boolean);render()}catch(e){msg(e.message,true)}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==b.dataset.view);$('title').textContent=b.textContent.trim();$('crumb').textContent='ÉPITHÈTE'});$('refresh').onclick=refresh;$('search').oninput=renderDone;$('selectAll').onchange=e=>{document.querySelectorAll('.pick').forEach(x=>{x.checked=e.target.checked;if(x.checked)selectedIds.add(x.value);else selectedIds.delete(x.value)})};
$('assignSelected').onclick=async()=>{const ids=[...selectedIds],agent=$('agentName').value.trim();if(!ids.length)return msg('Sélectionnez au moins une ligne.',true);if(!agent)return msg('Choisissez un agent.',true);try{const r=await api('assign',{ids,agent});selectedIds.clear();$('selectAll').checked=false;msg(r.affectees+' ligne(s) affectée(s) à '+agent+'.');await refresh()}catch(e){msg(e.message,true)}};
$('addAgent').onclick=async()=>{const name=$('newAgent').value.trim();if(!name)return msg('Saisissez le nom de session Windows de l’agent.',true);try{await api('agents',{name});$('newAgent').value='';msg('Agent '+name.toUpperCase()+' ajouté.');await refresh();$('agentName').value=name.toUpperCase()}catch(e){msg(e.message,true)}};
$('exportDone').onclick=async()=>{const b=$('exportDone');b.disabled=true;b.textContent='Export en cours...';try{const r=await api('export',{});let text=r.exportees+' ligne(s) exportée(s) dans '+r.fichiers+' fichier(s) Excel.';if(r.erreurs?.length)text+=' '+r.erreurs.join(' | ');msg(text,!!r.erreurs?.length);await refresh()}catch(e){msg(e.message,true)}finally{b.disabled=false;b.textContent='Exporter vers Excel'}};
$('disconnect').onclick=async()=>{if(!confirm('Arrêter le serveur Manager ?'))return;const b=$('disconnect');b.disabled=true;try{await api('shutdown',{});document.body.innerHTML='<main class="offline"><h1>Manager déconnecté</h1><p>Le serveur a été arrêté. Vous pouvez fermer cette fenêtre.</p></main>'}catch(e){msg(e.message,true);b.disabled=false}};
$('saveConfig').onclick=async()=>{try{await api('config',{sourceDirectory:$('sourceDirectory').value.trim()});msg('Chemin source enregistré.');await refresh()}catch(e){msg(e.message,true)}};$('importFiles').onclick=async()=>{const b=$('importFiles');b.disabled=true;try{const r=await api('import',{});msg(r.ajoutees+' nouvelle(s) ligne(s) importée(s) depuis '+r.fichiers+' fichier(s).');await refresh()}catch(e){msg(e.message,true)}finally{b.disabled=false}};refresh();setInterval(()=>{if(!document.hidden)refresh()},10000);
